name: Build Examples

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build example projects
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore examples
    - name: Build
      run: dotnet build --no-restore examples
